// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-NWTVwkyVIbQb87LTFZJJp-UI-6cN0QI',
    appId: '1:926414309147:web:ddea690abdf1340b1035be',
    messagingSenderId: '926414309147',
    projectId: 'cet158quiz',
    authDomain: 'cet158quiz.firebaseapp.com',
    storageBucket: 'cet158quiz.firebasestorage.app',
    measurementId: 'G-0E4L36KVVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBBLZactnKoVI22pLWOtIkc6DHHjCGzIc',
    appId: '1:926414309147:android:c8422067c379ebaf1035be',
    messagingSenderId: '926414309147',
    projectId: 'cet158quiz',
    storageBucket: 'cet158quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWVquiere2zjY0MMyrbrX06wGXwmk6wg',
    appId: '1:926414309147:ios:96bed14b4aa74b181035be',
    messagingSenderId: '926414309147',
    projectId: 'cet158quiz',
    storageBucket: 'cet158quiz.firebasestorage.app',
    iosBundleId: 'com.example.cet158quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWVquiere2zjY0MMyrbrX06wGXwmk6wg',
    appId: '1:926414309147:ios:96bed14b4aa74b181035be',
    messagingSenderId: '926414309147',
    projectId: 'cet158quiz',
    storageBucket: 'cet158quiz.firebasestorage.app',
    iosBundleId: 'com.example.cet158quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-NWTVwkyVIbQb87LTFZJJp-UI-6cN0QI',
    appId: '1:926414309147:web:c701f869002321061035be',
    messagingSenderId: '926414309147',
    projectId: 'cet158quiz',
    authDomain: 'cet158quiz.firebaseapp.com',
    storageBucket: 'cet158quiz.firebasestorage.app',
    measurementId: 'G-YPCWLRBYXR',
  );
}
